# IO Recorder config
msg_arrival_threshold: 0.05 # seconds

# Controller config
left_wheel_motor: 4
right_wheel_motor: 1
left_vertical_motor: 2
right_vertical_motor: 3
# shrimp:   4 1 2 3
# bean:     2 1 4 3
# wayfarer: ? ? ? ?
