# Robot parameters
motor_width: 0.5 # meters
wheel_radius: 0.5 # meters
max_speed: 0.4 # m/s
max_rotation_rate: 70 # rad/s
max_torque: 70 # N*m

# Control parameters
kp: 0.1
ki: 0.0
kd: 0.0001
speed: 0.3 # m/s

# Joystick parameters
joy_kill_switch: -1 # -1 to disable
joy_deadzone: 0.01 # deadzone in [0,1]

motor_frequency: 2000 # Hz

low_throttle: 50 # %, for lowest speed
high_throttle: 100 # %, for highest speed
# for shrimp:   50 -> 100
# for bean:     0  -> 40
# for wayfarer: ?  -> ?
